### ISSUE TITLE
Workflow Error

### ISSUE THREAD

**Issue by lightninginabox** [aniongithub/rhasspy-appliance#1]
I tried creating a template called BTCPi and ran into the attached error when running them manual workflow. 

![Capture](https://user-images.githubusercontent.com/92657862/137629948-ba831e35-1327-4729-9296-687996cd3c1b.JPG)

Also I am looking for a way to create an image that runs a post installation script.  The script formats an external drive, creates a couple folders and runs another script that installs a docker application.  The complete script is here https://github.com/lightninginabox/btcpayserver-doc/blob/master/docs/Deployment/rpi4_install.sh.  

I am interested in your thoughts on how to create such an image.

**Comment by aniongithub** [comment]
Hi - I'd suggest moving this issue to the [pi-bootstrap](https://github.com/aniongithub/pi-bootstrap) repo instead, as that's the generic template meant to be used in different projects.

If the build completed fine and uploading failed, I'd check to see if you have enough space on Github, I've encountered this error when my storage was maxed out.

Edit: After reading your script it seems you need access to a mounted drive, so I suggest using a systemd service like the one I use in rhasspy - [bootstrap.sh](https://github.com/aniongithub/rhasspy-appliance/blob/main/etc/rhasspy/bootstrap.sh)

**Comment by lightninginabox** [comment]
Thanks. I think I got it to work.  I borrowed another idea that I found; creating a 'firstboot' service to setup the external drive, configure the firewall and run a docker service. 

https://github.com/lightninginabox/BTCPi/blob/main/modules/firstboot.Pifile

**Comment by aniongithub** [comment]
I think this could be a common enough thing that I plan to add a module to pi-bootstrap for a configurable first-run service. Glad you found a way forward for now!
